import 'dart:ui';
import 'package:get/get.dart';
import 'package:get/get_navigation/src/root/internacionalization.dart';
import 'assets.gen.dart';


enum Language {
  english(
    Locale('en', 'US'),
    Assets.english,
    'English',
  ),
  dutch(
    Locale('nl', 'NL'),
    Assets.dutch,
    'Dutch',
  ),
  german(
    Locale('de', 'DE'),
    Assets.german,
    'German',
  ),
  iran(
    Locale('fa', 'FA'),
    Assets.iran,
    'Persian',
  ),
  arabic(
    Locale('ar', 'AR'),
    Assets.arabic,
    'Arabic',
  ),
  french(
    Locale('fr', 'FR'),
    Assets.french,
    'French',
  );

  const Language(this.value, this.image, this.text);

  final Locale value;
  final AssetGenImage image;
  final String text;
}


class Languages extends Translations{

  @override
  Map<String,Map<String,String>> get keys=>{
    'en_US':{
      'Settings':'Settings',
      'Contacts':'Contacts',
      'Favorite':'Favorite',
      'Sort':'Sort',
      'Search':'Search',
      'Recent Added':'Recent Added',
      'Edit':'Edit',
      'Notifications add Sounds':'Notifications add Sounds',
      'Font':'Font',
      'History':'History',
      'Language':'Language',
      'Help':'Help',
      'Ask a Question':'Ask a Question',
      'About this app':'About this app',
      'Features':'Features',
      'Full Name':'Full Name',
      'Mobile Number':'Mobile Number',
      'Home Number':'Home Number',
      'Work Number':'Work Number',
      'More Info':'More Info',
      'Add':'Add',
      'Contact Numbers':'Contact Numbers',
      'Mobile':'Mobile',
      'Home':'Home',
      'Work':'Work',
      'Name':'Name',
      'Edit Contact':'Edit Contact',
      'Delete Contact':'Delete Contact',
      'Are you sure you want to delete this contact?':'Are you sure you want to delete this contact?',
      'Delete':'Delete',
      'Cancel':'Cancel',
    },

    'nl_NL':{
      "Settings": "Instellingen",
      "Contacts": "Contacten",
      "Favorite": "Favorieten",
      "Sort": "Sorteren",
      "Search": "Zoeken",
      "Recent Added": "Recent toegevoegd",
      "Edit": "Bewerken",
      "Notifications add Sounds": "Meldingen en geluiden",
      "Font": "Lettertype",
      "History": "Geschiedenis",
      "Language": "Taal",
      "Help": "Hulp",
      "Ask a Question": "Een vraag stellen",
      "About this app": "Over deze app",
      "Features": "Functies",
      "Full Name": "Volledige naam",
      "Mobile Number": "Mobiel nummer",
      "Home Number": "Huisnummer",
      "Work Number": "Werknummer",
      "More Info": "Meer informatie",
      "Add": "Toevoegen",
      "Contact Numbers": "Contactnummers",
      "Mobile": "Mobiel",
      "Home": "Huis",
      "Work": "Werk",
      "Name": "Naam",
      "Edit Contact": "Contact bewerken",
      "Delete Contact": "Contact verwijderen",
      "Are you sure you want to delete this contact?": "Weet je zeker dat je dit contact wilt verwijderen?",
      "Delete": "Verwijderen",
      "Cancel": "Annuleren"
    },

    'fa_FA':{
      "Settings": "تنظیمات",
      "Contacts": "مخاطبین",
      "Favorite": "موردعلاقه",
      "Sort": "مرتب‌",
      "Search": "جستجو",
      "Recent Added": "تازه اضافه‌شده‌ها",
      "Edit": "ویرایش",
      "Notifications add Sounds": "اعلان‌ها و صداها",
      "Font": "فونت",
      "History": "تاریخچه",
      "Language": "زبان",
      "Help": "راهنما",
      "Ask a Question": "پرسش سوال",
      "About this app": "درباره این اپلیکیشن",
      "Features": "ویژگی‌ها",
      "Full Name": "نام کامل",
      "Mobile Number": "شماره موبایل",
      "Home Number": "شماره منزل",
      "Work Number": "شماره محل کار",
      "More Info": "اطلاعات بیشتر",
      "Add": "اضافه کردن",
      "Contact Numbers": "شماره‌های تماس",
      "Mobile": "موبایل",
      "Home": "منزل",
      "Work": "محل کار",
      "Name": "نام",
      "Edit Contact": "ویرایش مخاطب",
      "Delete Contact": "حذف مخاطب",
      "Are you sure you want to delete this contact?": "آیا مطمئن هستید که می‌خواهید این مخاطب را حذف کنید؟",
      "Delete": "حذف",
      "Cancel": "لغو"
    },

    'fr_FR':{
      "Settings": "Paramètres",
      "Contacts": "Contacts",
      "Favorite": "Favoris",
      "Sort": "Trier",
      "Search": "Rechercher",
      "Recent Added": "Récemment ajouté",
      "Edit": "Modifier",
      "Notifications add Sounds": "Notifications et sons",
      "Font": "Police",
      "History": "Historique",
      "Language": "Langue",
      "Help": "Aide",
      "Ask a Question": "Poser une question",
      "About this app": "À propos de cette application",
      "Features": "Fonctionnalités",
      "Full Name": "Nom complet",
      "Mobile Number": "Numéro mobile",
      "Home Number": "Numéro de domicile",
      "Work Number": "Numéro professionnel",
      "More Info": "Plus d'infos",
      "Add": "Ajouter",
      "Contact Numbers": "Numéros de contact",
      "Mobile": "Mobile",
      "Home": "Domicile",
      "Work": "Travail",
      "Name": "Nom",
      "Edit Contact": "Modifier le contact",
      "Delete Contact": "Supprimer le contact",
      "Are you sure you want to delete this contact?": "Êtes-vous sûr de vouloir supprimer ce contact?",
      "Delete": "Supprimer",
      "Cancel": "Annuler"
    },

    'ar_AR':{
      "Settings": "الإعدادات",
      "Contacts": "جهات الاتصال",
      "Favorite": "المفضلة",
      "Sort": "فرز",
      "Search": "بحث",
      "Recent Added": "أُضيف حديثًا",
      "Edit": "تعديل",
      "Notifications add Sounds": "الإشعارات والأصوات",
      "Font": "الخط",
      "History": "السجل",
      "Language": "اللغة",
      "Help": "مساعدة",
      "Ask a Question": "طرح سؤال",
      "About this app": "عن هذا التطبيق",
      "Features": "الميزات",
      "Full Name": "الاسم الكامل",
      "Mobile Number": "رقم الجوال",
      "Home Number": "رقم المنزل",
      "Work Number": "رقم العمل",
      "More Info": "مزيد من المعلومات",
      "Add": "إضافة",
      "Contact Numbers": "أرقام الاتصال",
      "Mobile": "الجوال",
      "Home": "المنزل",
      "Work": "العمل",
      "Name": "الاسم",
      "Edit Contact": "تعديل جهة الاتصال",
      "Delete Contact": "حذف جهة الاتصال",
      "Are you sure you want to delete this contact?": "هل أنت متأكد أنك تريد حذف جهة الاتصال هذه؟",
      "Delete": "حذف",
      "Cancel": "إلغاء"
    },

    'de_DE':{
      "Settings": "Einstellungen",
      "Contacts": "Kontakte",
      "Favorite": "Favoriten",
      "Sort": "Sortieren",
      "Search": "Suchen",
      "Recent Added": "Kürzlich hinzugefügt",
      "Edit": "Bearbeiten",
      "Notifications add Sounds": "Benachrichtigungen und Töne",
      "Font": "Schriftart",
      "History": "Verlauf",
      "Language": "Sprache",
      "Help": "Hilfe",
      "Ask a Question": "Eine Frage stellen",
      "About this app": "Über diese App",
      "Features": "Funktionen",
      "Full Name": "Vollständiger Name",
      "Mobile Number": "Handynummer",
      "Home Number": "Festnetznummer",
      "Work Number": "Arbeitsnummer",
      "More Info": "Mehr Informationen",
      "Add": "Hinzufügen",
      "Contact Numbers": "Kontaktnummern",
      "Mobile": "Handy",
      "Home": "Zuhause",
      "Work": "Arbeit",
      "Name": "Name",
      "Edit Contact": "Kontakt bearbeiten",
      "Delete Contact": "Kontakt löschen",
      "Are you sure you want to delete this contact?": "Sind Sie sicher, dass Sie diesen Kontakt löschen möchten?",
      "Delete": "Löschen",
      "Cancel": "Abbrechen"
    }


  };
}
